# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2026-04-07 10:16:15
"""
import arcpy
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *
from arcpy.sa import *

def Model():  # Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("3D")
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    NSIDC8mDEM_Elevation = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_Elevation")
    Sentinel2_LandCover = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\Sentinel2_LandCover")
    USGS30mDEM_Aspect = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\USGS30mDEM_Aspect")
    Cost_Raster = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    START_South1_ChukhungValley = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\START_South1_ChukhungValley"
    CAMP_South1_basecamp = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_basecamp"
    South1_A = "POIs\\LCP Points\\South Route\\South1_A"
    South1_B = "POIs\\LCP Points\\South Route\\South1_B"
    Cost_Raster_3_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_campI_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campI"
    CAMP_South1_campII = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campII"
    Cost_Raster_2_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_basecamp_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_basecamp"
    CAMP_South1_campI = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campI"
    Cost_Raster_4_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_campII_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campII"
    CAMP_South1_campIII = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campIII"
    Cost_Raster_5_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_campIII_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campIII"
    CAMP_South1_campIV = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campIV"
    Cost_Raster_7_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_campIV_3_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campIV"
    Summit_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Summit"
    Cost_Raster_6_ = arcpy.Raster("C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Cost_Raster")
    CAMP_South1_campIV_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\CAMP_South1_campIV"
    Summit = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\Summit"

    # Process: Slope (Pct RIse) (Slope) (sa)
    NSIDC8mDEM_SlopePctRise = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopePctRise"
    Slope_Pct_RIse_ = NSIDC8mDEM_SlopePctRise
    NSIDC8mDEM_SlopePctRise = arcpy.sa.Slope(NSIDC8mDEM_Elevation, "PERCENT_RISE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    NSIDC8mDEM_SlopePctRise.save(Slope_Pct_RIse_)


    # Process: Slope (Angle) (Slope) (sa)
    NSIDC8mDEM_SlopeDegree = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree"
    Slope_Angle_ = NSIDC8mDEM_SlopeDegree
    NSIDC8mDEM_SlopeDegree = arcpy.sa.Slope(NSIDC8mDEM_Elevation, "DEGREE", 1, "PLANAR", "METER", "GPU_THEN_CPU")
    NSIDC8mDEM_SlopeDegree.save(Slope_Angle_)


    # Process: Reclassify (Reclassify) (sa)
    LandCover_reclassified = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\LandCover_reclassified"
    Reclassify = LandCover_reclassified
    LandCover_reclassified = arcpy.sa.Reclassify(Sentinel2_LandCover, "Value", "0 NODATA;1 NODATA;2 5;3 NODATA;4 NODATA;5 NODATA;6 NODATA;7 0;8 10;9 1;10 NODATA;11 2", "DATA")
    LandCover_reclassified.save(Reclassify)


    # Process: Resample (Resample) (management)
    Cost1_8m_basecost = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost1_8m_basecost"
    with arcpy.EnvManager(extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", snapRaster="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree"):
        arcpy.management.Resample(in_raster=LandCover_reclassified, out_raster=Cost1_8m_basecost)
        Cost1_8m_basecost = arcpy.Raster(Cost1_8m_basecost)

    # Process: Raster Calculator: Basecost (land cover) X Slope (degrees) (RasterCalculator) (sa)
    Cost2_8m_basecostXslope = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost2_8m_basecostXslope"
    Raster_Calculator_Basecost_land_cover_X_Slope_degrees_ = Cost2_8m_basecostXslope
    with arcpy.EnvManager(cellSize="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree"):
        Cost2_8m_basecostXslope = SetNull(NSIDC8mDEM_SlopeDegree > 60,    Con(Cost1_8m_basecost <= 0, 0.01, Cost1_8m_basecost) 	* (1 + (NSIDC8mDEM_SlopeDegree / 10.0) * (NSIDC8mDEM_SlopeDegree / 10.0))	)
        Cost2_8m_basecostXslope.save(Raster_Calculator_Basecost_land_cover_X_Slope_degrees_)


    # Process: Roughness (3x3 Nearest Neighborhood) (FocalStatistics) (sa)
    NSIDC8mDEM_Roughness = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_Roughness"
    Roughness_3x3_Nearest_Neighborhood_ = NSIDC8mDEM_Roughness
    NSIDC8mDEM_Roughness = arcpy.sa.FocalStatistics(NSIDC8mDEM_Elevation, "Rectangle 3 3 CELL", "STD", "DATA", 90)
    NSIDC8mDEM_Roughness.save(Roughness_3x3_Nearest_Neighborhood_)


    # Process: Raster Calculator: Basecost (LC) X Slope (degrees) X Roughness (idx) (RasterCalculator) (sa)
    Cost3_8m_basecostXslopeXroughness = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost3_8m_basecostXslopeXroughness"
    Raster_Calculator_Basecost_LC_X_Slope_degrees_X_Roughness_idx_ = Cost3_8m_basecostXslopeXroughness
    with arcpy.EnvManager(cellSize="INTERMEDIATE\\Cost2_8m_basecostXslope", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="INTERMEDIATE\\Cost2_8m_basecostXslope"):
        Cost3_8m_basecostXslopeXroughness =  Cost2_8m_basecostXslope *  (NSIDC8mDEM_Roughness * 0.1)
        Cost3_8m_basecostXslopeXroughness.save(Raster_Calculator_Basecost_LC_X_Slope_degrees_X_Roughness_idx_)


    # Process: Resample: turn 30m DEM Apsect into 8m DEM Aspect (Resample) (management)
    USGS8mDEM_Aspect = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\USGS8mDEM_Aspect"
    with arcpy.EnvManager(extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", resamplingMethod="NEAREST", 
                          snapRaster="INTERMEDIATE\\Cost3_8m_basecostXslopeXroughness"):
        arcpy.management.Resample(in_raster=USGS30mDEM_Aspect, out_raster=USGS8mDEM_Aspect, resampling_type="NEAREST")
        USGS8mDEM_Aspect = arcpy.Raster(USGS8mDEM_Aspect)

    # Process: Reclassify: add penalties for cardinal quadrant (Reclassify) (sa)
    Aspect_reclassified = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Aspect_reclassified"
    Reclassify_add_penalties_for_cardinal_quadrant = Aspect_reclassified
    with arcpy.EnvManager(cellSize="INTERMEDIATE\\Cost3_8m_basecostXslopeXroughness", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="INTERMEDIATE\\Cost3_8m_basecostXslopeXroughness"):
        Aspect_reclassified = arcpy.sa.Reclassify(USGS8mDEM_Aspect, "VALUE", "0 90 4;90 180 2;180 270 1;270 360 3", "NODATA")
        Aspect_reclassified.save(Reclassify_add_penalties_for_cardinal_quadrant)


    # Process: Raster Calculator: light penalty on aspect for Northern hemisphere (RasterCalculator) (sa)
    Cost4_8m_basecostXslopeXroughnessXaspect = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost4_8m_basecostXslopeXroughnessXaspect"
    Raster_Calculator_light_penalty_on_aspect_for_Northern_hemisphere = Cost4_8m_basecostXslopeXroughnessXaspect
    with arcpy.EnvManager(cellSize="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost3_8m_basecostXslopeXroughness", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost3_8m_basecostXslopeXroughness"):
        Cost4_8m_basecostXslopeXroughnessXaspect =  Cost3_8m_basecostXslopeXroughness * (Aspect_reclassified * 0.1)
        Cost4_8m_basecostXslopeXroughnessXaspect.save(Raster_Calculator_light_penalty_on_aspect_for_Northern_hemisphere)


    # Process: Reclassify: identify avalanche zones (30-45 degree slope) (Reclassify) (sa)
    Avalanche_Zones = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\Avalanche_Zones"
    Reclassify_identify_avalanche_zones_30_45_degree_slope_ = Avalanche_Zones
    with arcpy.EnvManager(cellSize="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_input_data.gdb\\NSIDC8mDEM_SlopeDegree"):
        Avalanche_Zones = arcpy.sa.Reclassify(NSIDC8mDEM_SlopeDegree, "VALUE", "0 30 1;30 45 1000;45 180 1", "NODATA")
        Avalanche_Zones.save(Reclassify_identify_avalanche_zones_30_45_degree_slope_)


    # Process: Raster Calculator: heavy penalty on avalanche zones (RasterCalculator) (sa)
    Cost5_8m_basecostXslopeXroughnessXaspectXavalanche = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost5_8m_basecostXslopeXroughnessXaspectXavalanche"
    Raster_Calculator_heavy_penalty_on_avalanche_zones = Cost5_8m_basecostXslopeXroughnessXaspectXavalanche
    Cost5_8m_basecostXslopeXroughnessXaspectXavalanche =  Cost4_8m_basecostXslopeXroughnessXaspect *  Avalanche_Zones
    Cost5_8m_basecostXslopeXroughnessXaspectXavalanche.save(Raster_Calculator_heavy_penalty_on_avalanche_zones)


    # Process: Raster Calculator: heavy penalty on elevation (RasterCalculator) (sa)
    Cost6_8m_basecostXslopeXroughnessXaspectXavalanche_elevation = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost6_8m_basecostXslopeXroughnessXaspectXavalancheXelevation"
    Raster_Calculator_heavy_penalty_on_elevation = Cost6_8m_basecostXslopeXroughnessXaspectXavalanche_elevation
    with arcpy.EnvManager(cellSize="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost5_8m_basecostXslopeXroughnessXaspectXavalanche", extent="472547.896997772 3078470.95655177 504065.612101196 3112235.77571591 PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", outputCoordinateSystem="PROJCRS[\"WGS_1984_UTM_Zone_45N\",BASEGEOGCRS[\"GCS_WGS_1984\",DYNAMIC[FRAMEEPOCH[1990.5],MODEL[\"AM0-2\"]],DATUM[\"D_WGS_1984\",ELLIPSOID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],CS[ellipsoidal,2],AXIS[\"Latitude (lat)\",north,ORDER[1]],AXIS[\"Longitude (lon)\",east,ORDER[2]],ANGLEUNIT[\"Degree\",0.0174532925199433]],CONVERSION[\"Transverse_Mercator\",METHOD[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",87.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0]],CS[Cartesian,2],AXIS[\"Easting (X)\",east,ORDER[1]],AXIS[\"Northing (Y)\",north,ORDER[2]],LENGTHUNIT[\"Meter\",1.0],ID[\"EPSG\",\"32645\"]]", 
                          snapRaster="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_cost_data.gdb\\Cost5_8m_basecostXslopeXroughnessXaspectXavalanche"):
        Cost6_8m_basecostXslopeXroughnessXaspectXavalanche_elevation =  Cost5_8m_basecostXslopeXroughnessXaspectXavalanche *  (NSIDC8mDEM_Elevation * 1000)
        Cost6_8m_basecostXslopeXroughnessXaspectXavalanche_elevation.save(Raster_Calculator_heavy_penalty_on_elevation)


    # Process: LCP: South1 A-B (LeastCostPath) (intelligence)
    LCP_South1_A = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_A"
    Output_Start_Point, Output_End_Point = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster, in_start_point=START_South1_ChukhungValley, in_end_point=CAMP_South1_basecamp, out_path_feature_class=LCP_South1_A)

    # Process: LCP: South1 C-D (LeastCostPath) (intelligence)
    Output_Path_Feature_Class = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_C"
    Output_Start_Point_2_, Output_End_Point_2_ = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster_3_, in_start_point=CAMP_South1_campI_2_, in_end_point=CAMP_South1_campII, out_path_feature_class=Output_Path_Feature_Class)

    # Process: LCP: South1 B-C (LeastCostPath) (intelligence)
    Output_Path_Feature_Class_2_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_B"
    Output_Start_Point_3_, Output_End_Point_3_ = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster_2_, in_start_point=CAMP_South1_basecamp_2_, in_end_point=CAMP_South1_campI, out_path_feature_class=Output_Path_Feature_Class_2_)

    # Process: LCP: D-E (LeastCostPath) (intelligence)
    Output_Path_Feature_Class_3_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_D"
    Output_Start_Point_4_, Output_End_Point_4_ = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster_4_, in_start_point=CAMP_South1_campII_2_, in_end_point=CAMP_South1_campIII, out_path_feature_class=Output_Path_Feature_Class_3_)

    # Process: LCP: E-F (LeastCostPath) (intelligence)
    Output_Path_Feature_Class_4_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_E"
    Output_Start_Point_5_, Output_End_Point_5_ = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster_5_, in_start_point=CAMP_South1_campIII_2_, in_end_point=CAMP_South1_campIV, out_path_feature_class=Output_Path_Feature_Class_4_)

    # Process: LCP: F-G (LeastCostPath) (intelligence)
    Output_Path_Feature_Class_5_ = "C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\Everest_LCP_data.gdb\\LCP_South1_F"
    Output_Start_Point_6_, Output_End_Point_6_ = arcpy.intelligence.LeastCostPath(in_cost_surface=Cost_Raster_7_, in_start_point=CAMP_South1_campIV_3_, in_end_point=Summit_2_, out_path_feature_class=Output_Path_Feature_Class_5_)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\G488_Project3_arcGISfolder.gdb", workspace="C:\\Users\\theoj\\OneDrive - The University of Montana\\Courses\\GPHY488\\Project3\\G488_Project3_arcGISfolder\\G488_Project3_arcGISfolder.gdb"):
        Model()
